# Generated by Django 5.1.5 on 2025-01-29 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarKeyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('number_of_buttons', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CarKey',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='locksmith',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='locksmith',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='locksmith',
            name='service_area',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locksmith',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='locksmith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locksmith'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='locksmith',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.locksmith'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('locksmith', 'Locksmith'), ('customer', 'Customer')], max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='car_key_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carkeydetails'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
