# Generated by Django 5.1.6 on 2025-02-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocksmithServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('admin_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminservice')),
                ('locksmith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locksmith')),
            ],
        ),
    ]
