# Generated by Django 5.1.6 on 2025-02-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_locksmithservices_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebid',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locksmithservices'),
        ),
    ]
