# Generated by Django 5.1.6 on 2025-02-26 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_servicebid_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locksmithservices'),
        ),
        migrations.DeleteModel(
            name='LocksmithService',
        ),
    ]
