# Generated by Django 5.1.5 on 2025-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_locksmith_latitude_locksmith_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsettings',
            options={'verbose_name': 'Admin Settings', 'verbose_name_plural': 'Admin Settings'},
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='created_at',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='platform_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
