# Generated by Django 5.1.5 on 2025-01-31 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_adminsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocksmithDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('pcc_file', models.FileField(upload_to='locksmiths/pcc/')),
                ('license_file', models.FileField(upload_to='locksmiths/license/')),
                ('photo', models.ImageField(upload_to='locksmiths/photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('locksmith', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.locksmith')),
            ],
        ),
    ]
