# Generated by Django 5.1.5 on 2025-02-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_locksmithdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='locksmith',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='locksmith',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='locksmith',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locksmith',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='locksmiths/license/'),
        ),
        migrations.AddField(
            model_name='locksmith',
            name='pcc_file',
            field=models.FileField(blank=True, null=True, upload_to='locksmiths/pcc/'),
        ),
        migrations.AddField(
            model_name='locksmith',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='locksmiths/photos/'),
        ),
        migrations.AlterField(
            model_name='locksmith',
            name='service_area',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='LocksmithDetails',
        ),
    ]
