# Generated by Django 5.1.5 on 2025-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_locksmith_address_locksmith_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('locksmith', 'Locksmith'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
