# Generated by Django 5.1.6 on 2025-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locksmith',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
