# Generated by Django 5.1.5 on 2025-02-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp_enabled',
        ),
    ]
