# Generated by Django 5.1.6 on 2025-03-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_locksmith_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10),
        ),
    ]
