# Generated by Django 5.1.5 on 2025-02-10 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_totp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocksmithService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('key_cutting', 'Key cutting'), ('car_key_repair', 'Car Key Repair'), ('home_lock_repair', 'Home Lock Repair'), ('locked_unlocking', 'Locked Unlocking')], default='key_cutting', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('car_key_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carkeydetails')),
                ('locksmith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locksmith')),
            ],
        ),
    ]
