# Generated by Django 5.1.5 on 2025-02-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_locksmithservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='commission_percentage',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='locksmithservice',
            name='service_type',
            field=models.CharField(choices=[('key_duplication', 'Key Duplication'), ('car_key_repair', 'Car Key Repair'), ('home_lock_repair', 'Home Lock Repair'), ('locked_unlocking', 'Locked Unlocking')], default='key_duplication', max_length=255),
        ),
    ]
