# Generated by Django 5.1.6 on 2025-03-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_booking_payment_status_booking_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminservice',
            name='base_price',
        ),
    ]
