# Generated by Django 5.1.6 on 2025-03-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_adminservice_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='locksmithservices',
            name='car_key_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carkeydetails'),
        ),
    ]
