# Generated by Django 5.1.6 on 2025-04-21 06:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locksmith',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[api.models.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='locksmith',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[api.models.validate_longitude]),
        ),
    ]
