# Generated by Django 5.2 on 2025-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_locksmith_latitude_alter_locksmith_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
