# Generated by Django 5.2 on 2025-04-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_booking_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
