# Generated by Django 5.2 on 2025-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_booking_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_keys',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: number of keys the customer wants', null=True),
        ),
    ]
