# Generated by Django 5.2 on 2025-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_booking_number_of_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='locksmithservices',
            name='additional_key_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price charged per additional key', max_digits=10),
        ),
    ]
