# Generated by Django 5.2 on 2025-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_locksmithservices_additional_key_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price including base service and keys', max_digits=10, null=True),
        ),
    ]
