# Generated by Django 5.2 on 2025-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image related to the booking', null=True, upload_to='booking_images/'),
        ),
    ]
