# Generated by Django 5.2 on 2025-05-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_booking_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carkeydetails',
            name='year',
        ),
        migrations.AddField(
            model_name='carkeydetails',
            name='year_from',
            field=models.IntegerField(blank=True, help_text='Starting year (e.g. 2018)', null=True),
        ),
        migrations.AddField(
            model_name='carkeydetails',
            name='year_to',
            field=models.IntegerField(blank=True, help_text='Ending year (e.g. 2024)', null=True),
        ),
    ]
