# Generated by Django 5.2 on 2025-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_carkeydetails_year_carkeydetails_year_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminservice',
            name='description',
        ),
        migrations.AddField(
            model_name='adminservice',
            name='service_type',
            field=models.CharField(blank=True, choices=[('smart_lock', 'Smart Lock'), ('emergency', 'Emergency'), ('automotive', 'Automotive'), ('commercial', 'Commercial'), ('residential', 'Residential')], max_length=20, null=True),
        ),
    ]
