# Generated by Django 5.2 on 2025-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_adminservice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminservice',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='adminservice',
            unique_together={('name', 'service_type')},
        ),
    ]
