# Generated by Django 5.2 on 2025-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_locksmith_gst_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locksmith',
            name='gst_registered',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
