# Generated by Django 5.2 on 2025-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_locksmith_gst_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_customer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_locksmith_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
