# Generated by Django 5.2 on 2025-06-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_booking_locksmith_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
