# Generated by Django 5.2 on 2025-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_adminsettings_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='locksmith_transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount transferred to locksmith', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('completed', 'Completed')], default='not_started', help_text='Tracks the status of transfer to the locksmith', max_length=20),
        ),
    ]
