# Generated by Django 5.2 on 2025-06-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_websitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='locksmith',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
