# Generated by Django 5.2 on 2025-06-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_suggestedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedservice',
            name='additional_key_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Price per extra key', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedservice',
            name='service_type',
            field=models.CharField(choices=[('smart_lock', 'Smart Lock'), ('emergency', 'Emergency'), ('automotive', 'Automotive'), ('commercial', 'Commercial'), ('residential', 'Residential')], default=10, max_length=20),
            preserve_default=False,
        ),
    ]
