# Generated by Django 5.2 on 2025-07-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_cctvtechnicianpreregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedservice',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
